### ISSUE TITLE
ReferenceError: window is not defined

### ISSUE THREAD

**Issue by caperavensoftware** [aurelia/pal-browser#13]
```
Message:
    window is not defined
Stack:
ReferenceError: window is not defined
    at Object.<anonymous> (/Volumes/Projects/Mental Arena/Javascript/testing-issues/node_modules/aurelia-pal-browser/dist/commonjs/aurelia-pal-browser.js:21:13)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Volumes/Projects/Mental Arena/Javascript/testing-issues/node_modules/aurelia-bootstrapper/dist/commonjs/aurelia-bootstrapper.js:12:26)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Volumes/Projects/Mental Arena/Javascript/testing-issues/app/test/components/my-component/my-component-tests.js:9:28)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
```

In repository I have a test component that I want to test.
Repository:
https://github.com/caperavensoftware/testing-issues

Component
https://github.com/caperavensoftware/testing-issues/tree/master/src/components/my-component

Tests
https://github.com/caperavensoftware/testing-issues/blob/master/test/components/my-component/my-component-tests.js

```
var _PLATFORM = exports._PLATFORM = {
  location: **window.location,**
  history: **window.history,**
  addEventListener: function addEventListener(eventName, callback, capture) {
    this.global.addEventListener(eventName, callback, capture);
  },
  removeEventListener: function removeEventListener(eventName, callback, capture) {
    this.global.removeEventListener(eventName, callback, capture);
  },

  performance: window.performance,
  requestAnimationFrame: function requestAnimationFrame(callback) {
    return this.global.requestAnimationFrame(callback);
  }
};
```

when testing, using mocha there is no window object

**Comment by EisenbergEffect** [comment]
Todo Mocha testing, you'll want to use a different PAL implementation. There's one for nodejs.

**Comment by caperavensoftware** [comment]
How would I set aurelia to load a different PAL implementation?

**Comment by EisenbergEffect** [comment]
You need a different bootstrapper.

We're actually in the process of fixing all of this now. In the next few days we hope to release an update d bootstrapper that automatically loads the correct PAL based on the runtime.

**Comment by caperavensoftware** [comment]
ok i will look again on the next release, ty for all your effort

**Comment by MCGPPeters** [comment]
@EisenbergEffect Is there any news on the subject? Personally I'm using aurelia-bootstrapper-webpack, mocha and typescript and i'm having the same issues. I noticed that in the latest release you introduced a 'universal' bootstrapper (1.2.0) that  loads the correct PAL implementation depending on the run time environment (node / browser / electron etc ... ) and has webpack support as well if i'm correct. I tried to substitute aurelia-bootstrapper-webpack with aurelia-webpack, but didn't get it to work... Is that the way to go or is there another way to ('manually') load up the correct PAL implementation.. Thanks in advance...

**Comment by EisenbergEffect** [comment]
I'd look into using the default bootstrapper for everything if you can. That's our unified bootstrapper now.

**Comment by MCGPPeters** [comment]
@EisenbergEffect when I used the new bootstrapper for runtime purposes (node, mocha, ts-node, typescript) it complained about the fact it [could not find aurelia-pal-browser](https://www.screencast.com/t/qocxb0WuOW), while [the node module is present](https://www.screencast.com/t/DDtWixPEOVo).... Any ideas? 

Tnx again for your support...
